---
title: "Untitled"
author: "José Fernando Zea"
date: "17/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Partición Archivos Parquet

```{r, warning=FALSE, message=FALSE}
library(haven)
library(dplyr)
library(labelled)
library(data.table)
```

Se carga la función para escribir los archivos en formato parquet:

```{r, warning=FALSE, message=FALSE}
source("f_write_chunk_data.r", encoding = "UTf-8")
```


# Tabla de personas

El conjunto de datos de persona en csv se exporta a parquet para acelerar el procesamiento:

```{r, warning=FALSE, message=FALSE}
walk("../output/csv_31enero/personas.csv", write_chunk_data, "../output/2.parquet/personas",
     chunk_size = 500000)
```

# Tabla de viviendas

El conjunto de datos de viviendas en csv se exporta a parquet para acelerar el procesamiento:


```{r, warning=FALSE, message=FALSE}
walk("../output/csv_31enero/viviendas.csv", write_chunk_data, "../output/1.parquet/viviendas",
     chunk_size = 500000)
```
