---
title: "Untitled"
author: "José Fernando Zea"
date: "23/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(labeling)
library(arrow)
```

```{r}
viviendas <- open_dataset("../output/parquet/viviendas")
```

# Identificador vivienda

```{r}
cons_viv <- viviendas %>% group_by(I02_DEPTO, I03_PROV, I04_MUN, I06_CIUCOM, ID_UPM,   
                                   I10_MANZANA, I_BC_VIV) %>% summarise(num_casos = n()) %>%
  
            ungroup() %>% group_by(num_casos) %>% summarise(temp = n()) %>%
            collect()
cons_viv
```


```{r}
cons_personas <- personas %>% group_by(I02_DEPTO, I03_PROV, I04_SECC, I06_CIUCOM,  
                                   I10_MANZ, ID_BC_PERS) %>% summarise(num_casos = n()) %>%
  
                     ungroup() %>% group_by(num_casos) %>% summarise(temp = n()) %>%
            collect()
cons_personas
```


```{r}
cons_personasB <- personas %>% group_by(ID_BC_PERS) %>% summarise(num_casos = n()) %>%
  
                     ungroup() %>% group_by(num_casos) %>% summarise(temp = n()) %>%
            collect()
cons_personasB
```





```{r}
datos_etiqueta_personas <- readRDS("../output/etiquetas/personas_etiquetas.rds")
etiquetas <- var_label(datos_etiqueta)
etiquetas[sapply(etiquetas, is.null)] <- NA
a <- data.frame(variable = names(etiquetas), 
                etiqueta = etiquetas %>% as.character()
                )
viewxl::view_in_xl(a)

```


```{r}
datos_etiqueta_viviendas <- readRDS("../output/etiquetas/viviendas_etiquetas.rds")
etiquetas_viviendaetiquetas <- var_label(datos_etiqueta_viviendas)
 etiquetas_viviendaetiquetas[sapply(etiquetas_viviendaetiquetas, is.null)] <- NA
b <- data.frame(variable = names(etiquetas_viviendaetiquetas), 
                 etiqueta = etiquetas_viviendaetiquetas %>% as.character()
                 )
 viewxl::view_in_xl(b)

```


```{r}
personas <- open_dataset("../output/parquet/personas")
```


# Información geográfica

Los departamentos
```{r}
val_labels(datos_etiqueta$I02_DEPTO)
```

```{r}
cons_provincia <- personas %>% group_by(I02_DEPTO, I03_PROV) %>% summarise(temp = n()) %>% collect() %>% arrange(I02_DEPTO, I03_PROV)
```

https://www.bivica.org/files/municipios-Bolivia.pdf


```{r}
cons_municipio <- personas %>% group_by(I02_DEPTO, I03_PROV, I06_CIUCOM) %>% summarise(temp = n()) %>% collect() %>% arrange(I02_DEPTO, I03_PROV, I06_CIUCOM)
```



```{r}
cons_municipio <- personas %>% group_by(I02_DEPTO, I03_PROV, I04_SECC) %>% summarise(temp = n()) %>% collect() %>% arrange(I02_DEPTO, I03_PROV, I04_SECC)
```


```{r}
cons_municipio <- personas %>% group_by(I02_DEPTO, I03_PROV, I04_SECC, I06_CIUCOM) %>% summarise(temp = n()) %>% collect() %>% arrange(I02_DEPTO, I03_PROV, I04_SECC, I06_CIUCOM)
```




```{r}
cons_mz <- personas %>% group_by(I02_DEPTO, I03_PROV, I04_SECC, I06_CIUCOM, I10_MANZ) %>% summarise(temp = n()) %>% collect() %>% arrange(I02_DEPTO, I03_PROV, I04_SECC, I06_CIUCOM, I10_MANZ)
```

```{r}
# Código único manzana
cons_mz2 <- personas %>% group_by(ID_UNICO) %>% summarise(temp = n()) %>% collect() 
```




```{r}
# Código único manzana
cons_viv <- personas %>% group_by(ID_UNICO, I21_NROVIV) %>% summarise(temp = n()) %>% collect() 
```


# Viviendas





```{r}
cons_tablaviv_munic <- viviendas %>% group_by(I02_DEPTO, I03_PROV, I04_MUN) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_mun = n()) %>% collect()
cons_tablaviv_munic

```


```{r}
cons_tablaper_munic <- personas %>% group_by(I02_DEPTO, I03_PROV, I04_SECC) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_mun = n()) %>% collect()
cons_tablaviv_munic

```




```{r}
cons_tablaviv_ciudComun <- viviendas %>% group_by(I02_DEPTO, I03_PROV, I04_MUN, I06_CIUCOM) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_ciudComun = n()) %>% collect()
cons_tablaviv_ciudComun

```

```{r}
cons_tablaper_ciudComun <- personas %>% group_by(I02_DEPTO, I03_PROV, I04_SECC, I06_CIUCOM) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_ciudComun = n()) %>% collect()
cons_tablaper_ciudComun

```



```{r}
cons_tablaViv_ciudMZA <- viviendas %>% group_by(I02_DEPTO, I03_PROV, 
                           I04_MUN, I06_CIUCOM,ID_UPM, I10_MANZANA) %>%
                             summarise(cuenta = n()) %>%  collect()
                   
cons_tablaViv_ciudMZA
```


```{r}
cons_tablaViv_ciudMZ <- viviendas %>% group_by(I02_DEPTO, I03_PROV, 
                           I04_MUN, I06_CIUCOM, I10_MANZANA) %>%
                             summarise(cuenta = n()) %>%  collect()
                   
cons_tablaViv_ciudMZ
```

```{r}
cons_tablaViv_ciudMZ_B <- viviendas %>% group_by(id_unicoAD) %>%
                             summarise(cuenta = n()) %>%
                   ungroup() %>% 
                     summarise(num_MZ = n()) %>% collect()
cons_tablaViv_ciudMZ_B
```



```{r}
cons_tablaViv_ciudMZ <- viviendas %>% group_by(ID_UNICO) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_MZ = n()) %>% collect()
cons_tablaViv_ciudMZ
```



```{r}
cons_tablaper_ciudMZ2 <- personas %>% group_by(I02_DEPTO, I03_PROV, 
                           I04_SECC, I06_CIUCOM, I10_MANZ) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_MZ = n()) %>% collect()
cons_tablaper_ciudMZ2
```


```{r}
cons_tablaper_ciudMZ2 <- personas %>% group_by(ID_UNICO) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_MZ = n()) %>% collect()
cons_tablaper_ciudMZ2


```



```{r}
cons_tablaper_ciudMZ2 <- personas %>% group_by(ID_UNICO) %>% summarise(cuenta = n()) %>%
                   ungroup() %>% summarise(num_MZ = n()) %>% collect()
cons_tablaper_ciudMZ2


```







```{r}
cons_tablaViv_nroViv <- viviendas %>% group_by(ID_UNICO, I21_NROVIV) %>% 
                        summarise(cuenta = n()) %>%
                        ungroup() %>% summarise(num_MZ = n()) %>% collect()
cons_tablaViv_nroViv
```



```{r}
cons_tablaViv_nroViv <- personas %>% group_by(ID_UNICO, I21_NROVIV) %>% 
                        summarise(cuenta = n()) %>%
                        ungroup() %>% summarise(num_MZ = n()) %>% collect()
cons_tablaViv_nroViv
```