---
title: "Untitled"
author: "José Fernando Zea"
date: "21/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cargamos la librerías necesarias:

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(arrow)
```


```{r, warning=FALSE, message=FALSE}
setwd("funciones")
source("script_unionUPMS.r", encoding = "UTF-8")
```


```{r, warning=FALSE, message=FALSE}
setwd("../output/2.IndicaroresCenso")
consulta_hogar_nbi <- readRDS("consulta_hogar_nbi.rds")
```
Calculo NBI:

```{r}
consulta_hogar_nbi$NBI <- rowMeans(consulta_hogar_nbi[,-1])
```



```{r, warning=FALSE, message=FALSE}
setwd("../output/2.IndicaroresCenso")
consulta_ocupac <- readRDS("consulta_ocupac.rds")
```



Lectura archivo parquet de viviendas:

```{r, warning=FALSE, message=FALSE}
setwd("../output/2.parquet")
viviendas <- open_dataset("viviendas") %>% collect()
```

```{r, warning=FALSE, message=FALSE}
viviendas <- viviendas[!duplicated(viviendas$I_BC_VIV),]
consulta_hogar_nbi <- consulta_hogar_nbi[!duplicated(consulta_hogar_nbi$I_BC_VIV),]
gc(reset = T)
```


```{r}
viviendasNBI <- inner_join(viviendas %>% select(I02_DEPTO, I03_PROV,
                                            I04_MUN, I06_CIUCOM,  ID_UPM,URBRUR,
                                            I_BC_VIV) , consulta_hogar_nbi, 
                          by = "I_BC_VIV")

con <- viviendasNBI %>% group_by(I02_DEPTO, I03_PROV,
                                            I04_MUN, I06_CIUCOM,  ID_UPM) %>%
       count()
con$id_upm_inicial <- 1:nrow(con)
mean(con$n)
```



```{r}
con$n <- NULL
viviendasNBI <- left_join(viviendasNBI, con)
con2 <- viviendasNBI %>% group_by(I02_DEPTO, I03_PROV,
                                  I04_MUN, I06_CIUCOM,  id_upm_inicial) %>%
       count()
```

```{r}
gc(reset = T)
```

```{r}
consulta_ocupac <- consulta_ocupac %>% inner_join(viviendasNBI %>%                                                       select(I02_DEPTO, I03_PROV, I04_MUN, 
                        I06_CIUCOM, ID_UPM, URBRUR, 
                        I_BC_VIV,  id_upm_inicial), by = "I_BC_VIV")
gc()
```
Se implementa el algoritmo de partición:

```{r, warning=FALSE, message=FALSE}
algoritmo_union50 <- f_unionesUPM(df = con2, id_upm = "id_upm_inicial", n_upm = "n", umbral = 50)

df_upm50 <- algoritmo_union50$df_upmUniones %>% 
  select(id_upm_inicial, id_upm50 = union_upm) 
df_upm50$seqUnion <- NULL
```

```{r, warning=FALSE, message=FALSE}
algoritmo_union100 <- f_unionesUPM(df = con2, id_upm = "id_upm_inicial", n_upm = "n", umbral = 100)

df_upm100 <- algoritmo_union100$df_upmUniones %>% 
  select(id_upm_inicial, id_upm100 = union_upm) 
df_upm100$seqUnion <- NULL
```


Se integran las particiones a la tabla de vivienda

```{r, warning=FALSE, message=FALSE}
viviendasNBI <- viviendasNBI %>% 
  left_join(df_upm50, by = "id_upm_inicial") %>% 
  left_join(df_upm100, by = "id_upm_inicial")
gc(reset = T)
```
Integramos las particiones al archivo ocupacional:

```{r, warning=FALSE, message=FALSE}
consulta_ocupac  <- consulta_ocupac  %>% 
  left_join(df_upm50, by = "id_upm_inicial") %>% 
  left_join(df_upm100,by = "id_upm_inicial")
gc()
```



```{r, warning=FALSE, message=FALSE}
setwd("../output/3.ConformacionUPMCenso")
saveRDS(viviendasNBI, "viviendasNBI.rds")
saveRDS(consulta_ocupac, "consulta_ocupac.rds")

saveRDS(algoritmo_union50$df_upmUniones, "DetalleUniones50.rds")
saveRDS(algoritmo_union100$df_upmUniones, "DetalleUniones100.rds")
```